### ISSUE TITLE
Invalid types are generated and published

### ISSUE THREAD

**Issue by Gozala** [ipld/js-dag-cbor#24]
We had to disable lib check here https://github.com/ipfs-shipyard/nft.storage/pull/56#discussion_r628082097 because js-dag-cbor seems to have invalid types generated. Specifically:

```js
export const encode: (data: T) => import("multiformats/codecs/interface").ByteView<T>;
```

`T` generic type parameter is not declared for whatever reason. It maybe related to https://github.com/microsoft/TypeScript/issues/41258

**Comment by Gozala** [comment]
I'm suspecting this maybe causing the problem here

https://github.com/ipld/js-dag-cbor/blob/a49da7e8d4008c995c829c6cf04f2746ee39774b/index.js#L6

Since generics for statics is not a thing

**Comment by rvagg** [comment]
https://github.com/multiformats/js-multiformats/blob/96ff0043da2cfa158db966e4d22073141e9f9b3a/src/codecs/interface.ts#L26-L28

perhaps you could see a creative way to deal with this weird construct instead? I'd really like to not have this because it pushes the generic into the bytes portion of the encoder/decoder interface which is not needed cause it's always just `Uint8Array`

**Comment by rvagg** [comment]
Here's the other thing that bothers me about this - I have a TypeScript project in test/ts-use/ that tries to exercise the typing. What is it doing wrong that it's not picking up what you're experiencing?

**Comment by rvagg** [comment]
How about we just make `ByteView<T>` go away and stick with `Uint8Array` instead?

```typescript
export interface BlockEncoder<Code extends number> {
  name: string
  code: Code
  encode(data: any): Uint8Array
}
export interface BlockDecoder<Code extends number> {
  code: Code
  decode(bytes: Uint8Array): any
}
```

The one thing `T` has been nice for is dag-pb where we want strong typing on the object: https://github.com/ipld/js-dag-pb/blob/1e5ab163a94416631aeec92a3e92d347f3017375/src/index.js#L276-L284

On dag-cbor and dag-json we can handle a subset of `any` (I've been considering an IPLD Data Model recursive type that would properly cover it, but I think that's probably going to be way too user-hostile).

**Comment by Gozala** [comment]
> Here's the other thing that bothers me about this - I have a TypeScript project in test/ts-use/ that tries to exercise the typing. What is it doing wrong that it's not picking up what you're experiencing?

I would guess that it's is the problem with how ipjs does things, but I'd have to check. I have this setup in bunch of places where it works.

**Comment by Gozala** [comment]
P.S. I wanted to thread through `Code` into the `ByteView` as well so it would be even more useful and catch things like these

<img width="1289" alt="image" src="https://user-images.githubusercontent.com/21236/117867059-b3e01d80-b24c-11eb-8e0a-12b394bcc94a.png">

In the end I did not do it because I did not wanted to make scare folks away

**Comment by Gozala** [comment]
This may also explain a bit more why I was so keen on the whole `cbor.or(pb).or(jose)` pipelines as the composition would carry typing information allowing it to encode / decode either of those but reject anything else at compile time.

**Comment by Gozala** [comment]
> How about we just make `ByteView<T>` go away and stick with `Uint8Array` instead?

If the motivation here is to not have to type the `T` [this might be a better alternative](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgMIEkAiyDeBYAKGWTgGcNMAuNLQgX0MLAE8AHFTAQQHEA1OADYBXFAF5CxAD7IARgHs5AiHBATk0kEIC2M6GumkwUUAHN9yTQIHmKjAi3bIu3TlChxmyUU54A5OQAmEADaALpMbBw8APIyAFYQCGBeuMEA1hDMlIbGICah1M78whCSzq7uzGUx8YlgDPaRPtz+QSlFgiLqzbEJSd3lbh52oJCwiCgAQsyQvMAQAO4APKiBKBAAHpAgAaQW2rpQADTIACoAfMib27vIAKqjABwVHrhqCGsA-NSrQWoBcDAcG+p3oI3A0HgSGQkwEcgQaQAoiAPkEoCs1lcthAdntNDpoCdWutsbjkEIQGkQHIFiAUhSqTSQJd8EQrii1ktTlibntiecABTUoKUU4ASko01m82WvwgJwuYIIhFGkImMLhCMwiTW6LlPJxt3xhyJmOuhr2DOptPplOtzLebKCqIgXINZP5ApkMwgpElPrmiwxQQV5wloIIDTszoEcCgKAAbnH2cATFo4JLNUiOWilgBGAAMBcuADINfC0tqXejC8XCDG44nkwh5FBMxXkdX83mAEwnZz85Bl2EVqu67t95r8+uJWPx5BJqAkEAzAAWpmoI4RnfHBZOKmYpfLWp1ub3y8Pdg+IEMVzzKRxqfTADocS6BThkKuIFY5NQAEQLHIUACAE-7IHQYqENet5yEIyTeI+aZwM+zprAKEB5s+pACMASACnmYpQQQcFgM+36-sgAD0VHIAgKgAOTJIgSCkHsFFwsgch0laTILp0EDQdxsHwT2D4gE+KFoUEGGEYQpE9uRP6cTRshZguMpfmQyAOCgoAwMB6ZgMA3HIKQcjIMAySMgs7HKRZwB7GA37xlewnJAg97eC2wGvjmEAfsgWhZMgDGkEIMAwAxEHET5UCoaeAWeWKz7BdRtE2XsVlaXsaW6B8QikCgnl0XGxi+pZIAGUJN4eWJ3mtgl74gIs9xPC8zACkRKowMgAoID2YqOsQwC9QKulyL1A1eKI3gMXItRJAxQ2ssQxDTap1qWdZ9pZWAYU0Ng0jOL0dQDDwHVqHQVwCEVw1rRttEuXpO1MntB3yIoyggJIOSmJIxp6GyDRRgQqlFckjkWHIzH8cAoFTpi5lXG4wE1beCAAMwpHFfnvp+VkQFofoWK1ADKEBgAKwR5icPahENkFubVJApAezmmHj6GflolOroEXW4Dpq5QDSoWTAoWgAITRXQTMEDBzH1ReHN5E16EtQsbXgM8Qydd1BBwIpcSFWRuEZM+zmAs+JhyM+mhgKQXV2C7ypuzIcbqzJMhZsRdhAA), that would reduce that burden while retaining all the benefits

```ts
interface CID {
  asCID: CID
}

type DAGValue =
  | boolean
  | number
  | string
  | null
  | CID

type DAGArray = DAGNode[]
type DAGObject = {[key:string]: DAGValue|DAGArray|DAGObject}
type DAGNode = DAGValue | DAGObject | DAGArray

interface ByteView<Code extends number, T> extends Uint8Array {
  code?: Code
  data?:T
}

interface BlockEncoder<Code extends number, Node extends unknown = unknown> {
  encode<T extends Node>(node:T):ByteView<Code, T>
}

interface BlockDecoder<Code extends number, Node extends unknown = unknown> {
  decode<T extends Node>(bytes:ByteView<Code, T>):T
}


declare var enigma:BlockEncoder<100> & BlockDecoder<100>
declare var cbor:BlockEncoder<112, DAGNode> & BlockDecoder<112, DAGNode>
declare var anything: BlockEncoder<0, any> & BlockDecoder<0, any>

const e1 = enigma.encode({ hello: "world" })
const out = enigma.decode(e1.slice(1))
out.hello // can't access hello on unknown value
const out2 = enigma.decode(e1)
out2.hello // block view has type information so it knows hello is there

const c1 = cbor.encode({ my: 'suff' })
cbor.decode(c1).my // knows it has my becouse c1 carries info
const c2 = cbor.decode(new Uint8Array())
if (c2) {
  if (typeof c2 === 'object') {
    c2 // now it knowns it's CID | DAGObject | DAGArray
  } else {
    c2 // here it knowns it's boolean|string|number
  }
}

// set is not a vaild DAGNode so error
const c3 = cbor.encode({ items: new Set([1, 2]) })

const a = anything.encode({ method() { throw 'Boom!' }})
const a2 = anything.decode(new Uint8Array())
a2.just.like.that.go.nuts()






bar.decode(block)
```
